language: node_js
cache:
  timeout: 600
  directories:
    - node_modules
    - fundraising/apps/aragon-fundraising/node_modules
    - fundraising/apps/bancor-formula/node_modules
    - fundraising/apps/batched-bancor-market-maker/node_modules
    - fundraising/apps/tap/node_modules
    - fundraising/shared/interfaces/node_modules
    - fundraising/templates/multisig/node_modules
notifications:
  email: false
node_js:
  - '8'
install:
  - travis_wait 60 npm install
jobs:
  include:
    - stage: tests
      script: npm run lint
      name: 'Lint'
    - script: npm run test:aragon-fundraising
      name: 'Aragon Fundraising'
    - script: npm run test:tap
      name: 'Tap'
    # - stage: coverage
    #   script: npm run coverage:agent
    #   name: 'Agent'
    # - script: npm run coverage:finance
    #   name: 'Finance'
    # - script: npm run coverage:payroll
    #   name: 'Payroll'
    # - script: npm run coverage:survey
    #   name: 'Survey'
    # - script: npm run coverage:token-manager
    #   name: 'Token Manager'
    # - script: npm run coverage:vault
    #   name: 'Vault'
    # - script: npm run coverage:voting
    #   name: 'Voting'
    # - stage: integration
    #   script: npm run test:payroll:only:payday
    #   name: 'Payroll payday'
# after_success:
#   - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
